# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publcation_date',
            new_name='publication_date',
        ),
    ]
